---
- name: libevent - Decompress
  unarchive:
    src: "{{ remote_files_public_dir }}/{{ find_libevent_result.stdout | basename }}"
    dest: "{{ remote_files_public_dir }}"
    remote_src: yes

- name: libevent - Build
  command: "{{ item }}"
  args:
    chdir: "{{ remote_files_public_dir }}/{{ find_libevent_result.stdout | basename | regex_replace('(.+)\\.tar.*', '\\1') }}"
  with_items:
    - "./configure --prefix='{{ remote_install_dir }}'"
    - "make -j{{ ansible_processor_vcpus }}"

- name: libevent - Install
  become: "{{ sudo_install }}"
  command: "{{ item }}"
  args:
    chdir: "{{ remote_files_public_dir }}/{{ find_libevent_result.stdout | basename | regex_replace('(.+)\\.tar.*', '\\1') }}"
  with_items:
    - "make install"
