---
- name: libevent - Get name
  local_action: command find "{{ role_path }}/files/" -name "libevent-*.tar.*"
  register: find_libevent_result

- name: libevent
  block:
    - name: libevent - Download
      copy:
        src: "{{ find_libevent_result.stdout }}"
        dest: "{{ remote_files_public_dir }}/{{ find_libevent_result.stdout | basename }}"
      notify:
        - libevent - Decompress
        - libevent - Build
        - libevent - Install
  always:
    - meta: flush_handlers
    - name: libevent - Clean
      file:
        path: "{{ remote_files_public_dir }}/{{ find_libevent_result.stdout | basename | regex_replace('(.+)\\.tar.*', '\\1') }}"
        state: absent
