---
- name: .gitconfig - Copy
  copy:
    src: "{{ remote_files_private_dir }}/.gitconfig"
    dest: "{{ remote_home }}/.gitconfig"
    remote_src: yes

############################################################

- name: .git-completion.bash - Copy
  copy:
    src: "{{ remote_files_private_dir }}/.git-completion.bash"
    dest: "{{ remote_home }}/.git-completion.bash"
    remote_src: yes

############################################################

- name: .bashrc - Check exist
  stat:
    path: "{{ remote_home }}/.bashrc"
  register: find_bashrc_result

- name: .bashrc - Backup if exist
  copy:
    src: "{{ remote_home }}/.bashrc"
    dest: "{{ remote_home }}/.bashrc-{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
  when: find_bashrc_result.stat.exists

- name: .bashrc - Copy
  copy:
    src: "{{ remote_files_private_dir }}/.bashrc"
    dest: "{{ remote_home }}/.bashrc"
    remote_src: yes

- name: .bashrc - Update home
  replace:
    path: "{{ remote_home }}/.bashrc"
    regexp: "/home/winest"
    replace: "{{ remote_home }}"

- name: .bashrc - Update install path
  replace:
    path: "{{ remote_home }}/.bashrc"
    regexp: "export ANSIBLE_INSTALL_PATH=(.+)"
    replace: "export ANSIBLE_INSTALL_PATH=\"{{ remote_install_dir }}\""
